In [1]:
import pandas as pd
df = pd.read_excel("C:\\Users\\amanm\\Desktop\\IPL2023Matches.xlsx",index_col=None)

In [2]:
df

,Index,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,0,Titans,Super Kings,Titans,5 wickets,Ahmedabad (840),"Mar 31, 2023",Twenty20
1,1,Punjab Kings,KKR,Punjab Kings,7 runs,Mohali (1015),"Apr 1, 2023",Twenty20
2,2,Super Giants,Capitals,Super Giants,50 runs,Lucknow (3355),"Apr 1, 2023",Twenty20
3,3,Sunrisers,Royals,Royals,72 runs,Hyderabad (1981),"Apr 2, 2023",Twenty20
4,4,RCB,Mumbai,RCB,8 wickets,Bengaluru (683),"Apr 2, 2023",Twenty20
...,...,...,...,...,...,...,...,...
69,69,RCB,Titans,Titans,6 wickets,Bengaluru (683),"May 21, 2023",Twenty20
70,70,Super Kings,Titans,Super Kings,15 runs,Chennai (291),"May 23, 2023",Twenty20
71,71,Super Giants,Mumbai,Mumbai,81 runs,Chennai (291),"May 24, 2023",Twenty20
72,72,Titans,Mumbai,Titans,62 runs,Ahmedabad (840),"May 26, 2023",Twenty20
73,73,Titans,Super Kings,Super Kings,5 wickets,Ahmedabad (840),"May 28-29, 2023",Twenty20

In [3]:
df1 = pd.read_excel("C:\\Users\\amanm\\Desktop\\batting_IPL2023.xlsx")

In [4]:
df1

,Position to bat,BATTING,Dismissal,R,B,M,4s,6s,SR,Match,Match Number
0,0,Devon Conway,b Mohammed Shami,1,6,-,0,0,16.66,CSK vs GT,0
1,1,Ruturaj Gaikwad,c Shubman Gill b Joseph,92,50,-,4,9,184,CSK vs GT,0
2,2,Moeen Ali,c †Saha b Rashid Khan,23,17,-,4,1,135.29,CSK vs GT,0
3,3,Ben Stokes,c †Saha b Rashid Khan,7,6,-,1,0,116.66,CSK vs GT,0
4,4,Ambati Rayudu,b Little,12,12,-,0,1,100,CSK vs GT,0
...,...,...,...,...,...,...,...,...,...,...,...
1176,2,Shivam Dube,not out,32,21,49,0,2,152.38,GT vs CSK,73
1177,3,Ajinkya Rahane,c Shankar b Sharma,27,13,20,2,2,207.69,GT vs CSK,73
1178,4,Ambati Rayudu,c & b Sharma,19,8,8,1,2,237.5,GT vs CSK,73
1179,5,MS Dhoni (c)†,c Miller b Sharma,0,1,1,0,0,0,GT vs CSK,73
1180,6,Ravindra Jadeja,not out,15,6,14,1,1,250,GT vs CSK,73

In [6]:
df1.head(20)

,Position to bat,BATTING,Dismissal,R,B,M,4s,6s,SR,Match,Match Number
0,0,Devon Conway,b Mohammed Shami,1,6,-,0,0,16.66,CSK vs GT,0
1,1,Ruturaj Gaikwad,c Shubman Gill b Joseph,92,50,-,4,9,184,CSK vs GT,0
2,2,Moeen Ali,c †Saha b Rashid Khan,23,17,-,4,1,135.29,CSK vs GT,0
3,3,Ben Stokes,c †Saha b Rashid Khan,7,6,-,1,0,116.66,CSK vs GT,0
4,4,Ambati Rayudu,b Little,12,12,-,0,1,100,CSK vs GT,0
5,5,Shivam Dube,c Rashid Khan b Mohammed Shami,19,18,-,0,1,105.55,CSK vs GT,0
6,6,Ravindra Jadeja,c Shankar b Joseph,1,2,-,0,0,50,CSK vs GT,0
7,7,MS Dhoni (c)†,not out,14,7,-,1,1,200,CSK vs GT,0
8,8,Mitchell Santner,not out,1,3,-,0,0,33.33,CSK vs GT,0
9,0,Wriddhiman Saha †,c Dube b Hangargekar,25,16,-,2,2,156.25,CSK vs GT,0
10,1,Shubman Gill,c Gaikwad b Deshpande,63,36,-,6,3,175,CSK vs GT,0
11,2,Sai Sudharsan,c †Dhoni b Hangargekar,22,17,-,3,0,129.41,CSK vs GT,0
12,3,Hardik Pandya (c),b Jadeja,8,11,-,0,0,72.72,CSK vs GT,0
13,4,Vijay Shankar,c Santner b Hangargekar,27,21,-,2,1,128.57,CSK vs GT,0
14,5,Rahul Tewatia,not out,15,14,-,1,1,107.14,CSK vs GT,0
15,6,Rashid Khan,not out,10,3,-,1,1,333.33,CSK vs GT,0
16,0,Prabhsimran Singh,c †Rahmanullah Gurbaz b Southee,23,12,10,2,2,191.66,PBKS vs KKR,1
17,1,Shikhar Dhawan (c),b Varun,40,29,75,6,0,137.93,PBKS vs KKR,1
18,2,Bhanuka Rajapaksa,c Singh b Yadav,50,32,47,5,2,156.25,PBKS vs KKR,1
19,3,Jitesh Sharma †,c Yadav b Southee,21,11,13,1,2,190.9,PBKS vs KKR,1

In [14]:
df2 = pd.read_excel("C:\\Users\\amanm\\Desktop\\team.xlsx",index_col = None)

In [15]:
df2

,0,Unnamed: 1,MS Dhoni,Age:,41y 131d,Batting:,Right hand Bat,Bowling:,Right arm Medium,CSK
0,1,NaN,Devon Conway,Age:,31y 130d,Batting:,Left hand Bat,Bowling:,Right arm Medium,CSK
1,2,NaN,Ruturaj Gaikwad,Age:,25y 288d,Batting:,Right hand Bat,Bowling:,Right arm Offbreak,CSK
2,3,NaN,Ajinkya Rahane,Age:,34y 162d,Batting:,Right hand Bat,Bowling:,Right arm Medium,CSK
3,4,NaN,Shaik Rasheed,Age:,18y 52d,Batting:,Right hand Bat,Bowling:,Legbreak,CSK
4,5,NaN,Ambati Rayudu,Age:,37y 53d,Batting:,Right hand Bat,Bowling:,Right arm Offbreak,CSK
...,...,...,...,...,...,...,...,...,...,...
256,20,NaN,Bhuvneshwar Kumar,Age:,32y 283d,Batting:,Right hand Bat,Bowling:,Right arm Medium,SRH
257,21,NaN,Mayank Markande,Age:,25y 4d,Batting:,Right hand Bat,Bowling:,Legbreak,SRH
258,22,NaN,T Natarajan,Age:,31y 225d,Batting:,Left hand Bat,Bowling:,Left arm Medium,SRH
259,23,NaN,Adil Rashid,Age:,34y 271d,Batting:,Right hand Bat,Bowling:,Legbreak,SRH
260,24,NaN,Umran Malik,Age:,22y 358d,Batting:,Right hand Bat,Bowling:,Right arm Fast,SRH